version: '3.7'

services:
  mysql:
    image: mysql:5
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "CAXs3izCpYpKUPHw"
      MYSQL_DATABASE: "db_app"
      MYSQL_USER: "admin_db_app"
      MYSQL_PASSWORD: "CKU4vsaz3fuKxiUR"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  build_and_run:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:8080"
